import { Mulish } from "next/font/google";
import "../styles/globals.css";

import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import Footer from "@/components/Footer";

const mulish = Mulish({weight: ["200","300","400","500","700","800", "900", "1000"], subsets: ["latin"]})

export const metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={mulish.className}>
          <Navbar />
          <div className="grid lg:grid-cols-6 grid-cols-1 gap-x-5 bg-primary-white min-h-screen">
            <div>
              <div className="fixed left-0 top-0 h-screen w-1/6">
                <Sidebar />
              </div>
            </div>
            
            {children}
            <div className='lg:col-span-2 col-span-5 mt-5 space-y-8 lg:pr-8 px-5 rounded-md'>
              {/* <Newsletter /> */}
              {/* <Advertisement />
              <SupportUs /> */}
            </div>

            <Footer />
          </div>
      </body>
    </html>
  );
}
